const { useMemo, useState } = React;

const NAV_ITEMS = ["Dashboard","Client CRM","Quotes","Shipments","Containers","Suppliers & Agents","Customs Documents","Invoices","Tasks","AI Assistant"];
const shipmentStages = ["Booking Confirmed","Cargo Picked Up","Warehouse Received","Customs Clearance","Loaded on Vessel","In Transit","Arrived at Port","Out for Delivery","Delivered"];

const seed = {
  clients:[{id:"C-001",name:"Emma Johnson",company:"Skyline FBA Ventures",country:"USA",type:"Amazon Seller",email:"emma@skylinefba.com",phone:"+1 310 555 0189",whatsapp:"+1 310 555 0189",preferredMethod:"Sea Freight + DDP",lastContact:"2026-05-14",monthlyValue:120000,notes:"Ships monthly FBA replenishment to LAX and NY.",history:["2026-05-14: Requested quote revision."]},{id:"C-002",name:"Oliver Reed",company:"Britannia Imports Ltd",country:"UK",type:"Importer",email:"oliver@britanniaimports.co.uk",phone:"+44 20 7946 0120",whatsapp:"+44 7700 900210",preferredMethod:"Sea Freight",lastContact:"2026-05-13",monthlyValue:94000,notes:"Home organizers and textiles.",history:["2026-05-13: Discussed FOB Ningbo rates."]},{id:"C-003",name:"Lena Fischer",company:"Nordic Retail GmbH",country:"Germany",type:"Retailer",email:"lena@nordicretail.de",phone:"+49 40 555 1200",whatsapp:"+49 151 5600 8844",preferredMethod:"Rail + Truck",lastContact:"2026-05-12",monthlyValue:76000,notes:"ETA-sensitive imports.",history:[]},{id:"C-004",name:"Khalid Mansoor",company:"Desert Bridge Distribution",country:"UAE",type:"Distributor",email:"khalid@desertbridge.ae",phone:"+971 4 220 8800",whatsapp:"+971 50 221 8891",preferredMethod:"Air Freight",lastContact:"2026-05-15",monthlyValue:132000,notes:"Urgent consumer electronics.",history:[]},{id:"C-005",name:"Faisal Al-Harbi",company:"Riyadh Wholesale Hub",country:"Saudi Arabia",type:"Wholesale Buyer",email:"faisal@rwhub.sa",phone:"+966 11 455 0090",whatsapp:"+966 55 204 1190",preferredMethod:"Sea Freight + Truck",lastContact:"2026-05-11",monthlyValue:88000,notes:"Large furniture consignments.",history:[]}],
  quotes:[{id:"Q-2301",client:"Skyline FBA Ventures",origin:"Shenzhen",destination:"USA",method:"Sea",incoterm:"DDP",cargo:"Amazon FBA goods",qty:1200,cbm:42,gross:11800,chargeable:11800,cost:18650,margin:18,status:"Sent",breakdown:{freight:13000,trucking:1200,customs:900,docs:250,insurance:300,service:3000}}],
  shipments:[{id:"S-9901",client:"Skyline FBA Ventures",cargo:"Cosmetics packaging",origin:"Guangzhou",destination:"Los Angeles",mode:"Sea",incoterm:"DDP",cbm:28,weight:7900,container:"MSCU9021456",bl:"OOLU7791023",stage:"In Transit",eta:"2026-05-23",etd:"2026-05-05",supplier:"Guangzhou Beauty Pack Co.",agent:"Pacific Axis USA",value:68000},{id:"S-9902",client:"Britannia Imports Ltd",cargo:"Textiles",origin:"Yiwu",destination:"London",mode:"Rail",incoterm:"FOB",cbm:18,weight:5100,container:"LCL",bl:"RAILUK23901",stage:"Customs Clearance",eta:"2026-05-20",etd:"2026-05-09",supplier:"Yiwu Textile Source",agent:"EuroLink Brokers",value:47000}],
  containers:[{no:"MSCU9021456",type:"40HQ",seal:"SL99871",vessel:"MV Ever Summit",voyage:"EV2309",pol:"Yantian",pod:"Los Angeles",etd:"2026-05-05",eta:"2026-05-23",status:"In Transit",cargo:"Cosmetics packaging",cbm:61,utilization:91}],
  partners:[{company:"Shenzhen Prime Electronics",type:"Chinese Supplier",city:"Shenzhen",contact:"Mr. Lin",wechat:"lin-prime-sz",whatsapp:"+86 138 0012 6631",rating:4.8,leadTime:"5 days",reliability:93,notes:"Consistent export quality."}],
  docs:[{ship:"S-9901",client:"Skyline FBA Ventures",type:"Commercial Invoice",status:"Approved",upload:"2026-05-03",missing:"None",action:"Archive"}],
  invoices:[{id:"INV-2048",client:"Skyline FBA Ventures",shipment:"S-9901",amount:22600,issue:"2026-05-06",due:"2026-05-20",payment:"ACH",balance:0,margin:19,status:"Paid"}],
  tasks:[{title:"Follow up with client",assignee:"Nadia",priority:"High",due:"2026-05-17",client:"Skyline FBA Ventures",shipment:"S-9901",status:"In Progress"}]
};

const badgeClass=s=>`badge ${(s||"").toLowerCase().replace(/\s+/g,"-")}`;
const stagePct=s=>Math.max(0,Math.round(((shipmentStages.indexOf(s)+1)/shipmentStages.length)*100));

function Modal({open,title,children,onClose,onSave}){if(!open) return null; return <div className="modal-backdrop"><div className="modal"><h3>{title}</h3>{children}<div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSave}>Save</button></div></div></div>}

function App(){
  const [tab,setTab]=useState("Dashboard");
  const [search,setSearch]=useState("");
  const [selected,setSelected]=useState(null);
  const [aiText,setAiText]=useState("Select an AI shortcut to generate operational messaging.");
  const [db,setDb]=useState(seed);
  const [modal,setModal]=useState({open:false,type:"",form:{}});

  const openCreate=()=>{
    const map={"Client CRM":{type:"client",form:{name:"",company:"",country:"",type:"",email:"",phone:"",whatsapp:"",preferredMethod:"Sea Freight",lastContact:"2026-05-17",monthlyValue:0,notes:"",history:[]}},"Quotes":{type:"quote",form:{id:`Q-${Date.now().toString().slice(-4)}`,client:"",origin:"Shenzhen",destination:"USA",method:"Sea",incoterm:"FOB",cargo:"",qty:0,cbm:0,gross:0,chargeable:0,cost:0,margin:15,status:"Draft",breakdown:{freight:0,trucking:0,customs:0,docs:0,insurance:0,service:0}}},"Shipments":{type:"shipment",form:{id:`S-${Date.now().toString().slice(-4)}`,client:"",cargo:"",origin:"Guangzhou",destination:"Los Angeles",mode:"Sea",incoterm:"FOB",cbm:0,weight:0,container:"LCL",bl:"",stage:"Booking Confirmed",eta:"2026-05-30",etd:"2026-05-20",supplier:"",agent:"",value:0}},"Tasks":{type:"task",form:{title:"",assignee:"",priority:"Medium",due:"2026-05-20",client:"",shipment:"",status:"Open"}}};
    if(map[tab]) setModal({open:true,...map[tab]});
  };
  const saveModal=()=>{const {type,form}=modal; if(type==="client") setDb(v=>({...v,clients:[...v.clients,{...form,id:`C-${String(v.clients.length+1).padStart(3,"0")}`}] })); if(type==="quote") setDb(v=>({...v,quotes:[form,...v.quotes]})); if(type==="shipment") setDb(v=>({...v,shipments:[form,...v.shipments]})); if(type==="task") setDb(v=>({...v,tasks:[form,...v.tasks]})); setModal({open:false,type:"",form:{}}); };

  const metrics = useMemo(()=>({activeClients:db.clients.length,openQuotes:db.quotes.filter(q=>["Draft","Sent","Negotiating"].includes(q.status)).length,activeShipments:db.shipments.filter(s=>s.stage!=="Delivered").length,delayedShipments:db.shipments.filter(s=>new Date(s.eta)<new Date("2026-05-17")&&s.stage!=="Delivered").length,monthlyRevenue:db.invoices.reduce((a,i)=>a+i.amount,0),unpaidInvoices:db.invoices.filter(i=>i.balance>0).length,totalCbmShipped:db.shipments.reduce((a,s)=>a+Number(s.cbm||0),0),totalContainersShipped:db.containers.length,upcomingEtas:db.shipments.filter(s=>new Date(s.eta)>=new Date("2026-05-17")).length,urgentTasks:db.tasks.filter(t=>["Urgent","High"].includes(t.priority)).length}),[db]);

  const renderTable=(h,rows)=><table><thead><tr>{h.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows}</tbody></table>;

  return <div className="app">
    <aside className="sidebar"><h1>BZ Global Freight</h1><p>From China to the World, Freight Made Clear</p>{NAV_ITEMS.map(n=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>{setTab(n);setSelected(null);}}>{n}</button>)}</aside>
    <main className="main">
      <header className="topbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..."/><button className="primary" onClick={openCreate}>+ Add</button></header>
      {tab==="Dashboard"&&<><section className="metric-grid">{Object.entries(metrics).map(([k,v])=><article key={k} className="card"><h4>{k.replace(/([A-Z])/g," $1")}</h4><strong>{k.includes("Revenue")?`$${v.toLocaleString()}`:v}</strong></article>)}</section><section className="metric-grid small">{["Shipments in transit","Pending customs clearance","Payments overdue","Quotes waiting for client approval","Containers arriving this week"].map(c=><article key={c} className="card"><h4>{c}</h4><p>Live operational feed</p></article>)}</section></>}
      {tab==="Client CRM"&&renderTable(["Name","Company","Country","Type","Email","Phone","WhatsApp","Preferred","Last Contact","Monthly Value","Actions"],db.clients.filter(c=>JSON.stringify(c).toLowerCase().includes(search.toLowerCase())).map(c=><tr key={c.id} onClick={()=>setSelected(c)}><td>{c.name}</td><td>{c.company}</td><td>{c.country}</td><td>{c.type}</td><td>{c.email}</td><td>{c.phone}</td><td>{c.whatsapp}</td><td>{c.preferredMethod}</td><td>{c.lastContact}</td><td>${Number(c.monthlyValue).toLocaleString()}</td><td><button onClick={(e)=>{e.stopPropagation();setAiText(`Subject: Follow-up on shipments for ${c.company}\n\nHi ${c.name},\nHere is your latest shipment plan from China with ETA highlights...`)}}>AI follow-up</button></td></tr>))}
      {tab==="Quotes"&&renderTable(["ID","Client","Origin","Destination","Method","Incoterm","Cargo","Qty","CBM","Cost","Margin","Status","Update"],db.quotes.map(q=><tr key={q.id} onClick={()=>setSelected(q)}><td>{q.id}</td><td>{q.client}</td><td>{q.origin}</td><td>{q.destination}</td><td>{q.method}</td><td>{q.incoterm}</td><td>{q.cargo}</td><td>{q.qty}</td><td>{q.cbm}</td><td>${Number(q.cost).toLocaleString()}</td><td>{q.margin}%</td><td><span className={badgeClass(q.status)}>{q.status}</span></td><td><select value={q.status} onChange={(e)=>setDb(v=>({...v,quotes:v.quotes.map(x=>x.id===q.id?{...x,status:e.target.value}:x)}))}>{["Draft","Sent","Negotiating","Approved","Rejected","Expired"].map(s=><option key={s}>{s}</option>)}</select></td></tr>))}
      {tab==="Shipments"&&<section className="cards">{db.shipments.map(s=><article key={s.id} className="card" onClick={()=>setSelected(s)}><h3>{s.id} · {s.client}</h3><p>{s.origin} ➜ {s.destination} · {s.mode} · {s.incoterm}</p><p>{s.cargo} · {s.cbm} CBM · {s.weight}kg</p><p>Container {s.container} · BL {s.bl}</p><p><span className={badgeClass(s.stage)}>{s.stage}</span></p><div className="progress"><span style={{width:`${stagePct(s.stage)}%`}} /></div><small>ETD {s.etd} · ETA {s.eta}</small><div style={{marginTop:8}}><select value={s.stage} onClick={(e)=>e.stopPropagation()} onChange={(e)=>setDb(v=>({...v,shipments:v.shipments.map(x=>x.id===s.id?{...x,stage:e.target.value}:x)}))}>{shipmentStages.map(st=><option key={st}>{st}</option>)}</select></div></article>)}</section>}
      {tab==="Containers"&&renderTable(["Container","Type","Seal","Vessel","Voyage","POL","POD","ETD","ETA","Status","Cargo","CBM","Util%"],db.containers.map(c=><tr key={c.no}><td>{c.no}</td><td>{c.type}</td><td>{c.seal}</td><td>{c.vessel}</td><td>{c.voyage}</td><td>{c.pol}</td><td>{c.pod}</td><td>{c.etd}</td><td>{c.eta}</td><td><span className={badgeClass(c.status)}>{c.status}</span></td><td>{c.cargo}</td><td>{c.cbm}</td><td>{c.utilization}</td></tr>))}
      {tab==="Suppliers & Agents"&&renderTable(["Company","Type","City","Contact","WeChat","WhatsApp","Rating","Lead","Reliability","Notes","AI"],db.partners.map(p=><tr key={p.company}><td>{p.company}</td><td>{p.type}</td><td>{p.city}</td><td>{p.contact}</td><td>{p.wechat}</td><td>{p.whatsapp}</td><td>{p.rating}</td><td>{p.leadTime}</td><td>{p.reliability}</td><td>{p.notes}</td><td><button onClick={()=>setAiText(`Negotiation brief for ${p.company}: prioritize transit reliability, pickup SLAs, and document accuracy.`)}>AI brief</button></td></tr>))}
      {tab==="Customs Documents"&&renderTable(["Shipment","Client","Type","Status","Upload","Missing","Action"],db.docs.map((d,i)=><tr key={i}><td>{d.ship}</td><td>{d.client}</td><td>{d.type}</td><td><span className={badgeClass(d.status)}>{d.status}</span></td><td>{d.upload}</td><td>{d.missing}</td><td>{d.action}</td></tr>))}
      {tab==="Invoices"&&renderTable(["ID","Client","Shipment","Amount","Issue","Due","Payment","Balance","Margin","Status"],db.invoices.map(i=><tr key={i.id}><td>{i.id}</td><td>{i.client}</td><td>{i.shipment}</td><td>${i.amount.toLocaleString()}</td><td>{i.issue}</td><td>{i.due}</td><td>{i.payment}</td><td>${i.balance.toLocaleString()}</td><td>{i.margin}%</td><td><span className={badgeClass(i.status)}>{i.status}</span></td></tr>))}
      {tab==="Tasks"&&renderTable(["Title","Assignee","Priority","Due","Client","Shipment","Status","Update"],db.tasks.map((t,i)=><tr key={i}><td>{t.title}</td><td>{t.assignee}</td><td><span className={badgeClass(t.priority)}>{t.priority}</span></td><td>{t.due}</td><td>{t.client}</td><td>{t.shipment}</td><td><span className={badgeClass(t.status)}>{t.status}</span></td><td><select value={t.status} onChange={(e)=>setDb(v=>({...v,tasks:v.tasks.map((x,idx)=>idx===i?{...x,status:e.target.value}:x)}))}>{["Open","In Progress","Done","Blocked"].map(s=><option key={s}>{s}</option>)}</select></td></tr>))}
      {tab==="AI Assistant"&&<section className="card"><h3>BZ Global Freight AI Assistant</h3><div className="shortcuts">{["Generate shipment update","Write delay apology","Create quote message","Prepare customs checklist","Write payment reminder","Translate supplier message to Chinese","Explain DDP vs FOB to client","Summarize today’s urgent shipments"].map(s=><button key={s} onClick={()=>setAiText(`AI Output — ${s}\n\nPrepared operational text for BZ Global Freight.`)}>{s}</button>)}</div><textarea rows="10" value={aiText} readOnly/><button onClick={()=>navigator.clipboard?.writeText(aiText)}>Copy message</button></section>}
    </main>
    <aside className="detail"><h3>Detail Panel</h3>{selected?<pre>{JSON.stringify(selected,null,2)}</pre>:<p>Select a client, quote, or shipment.</p>}{selected?.breakdown&&<div className="card"><h4>Quote Cost Breakdown</h4>{Object.entries(selected.breakdown).map(([k,v])=><p key={k}>{k}: ${v.toLocaleString()}</p>)}<p><strong>Final client price:</strong> ${Math.round(selected.cost*(1+selected.margin/100)).toLocaleString()}</p><p><strong>Profit estimate:</strong> ${(selected.cost*(selected.margin/100)).toLocaleString()}</p></div>}</aside>
    <Modal open={modal.open} title={`Add ${modal.type}`} onClose={()=>setModal({open:false,type:"",form:{}})} onSave={saveModal}><div className="form-grid">{Object.keys(modal.form).filter(k=>k!=="history"&&k!=="breakdown").map(k=><label key={k}>{k}<input value={modal.form[k]} onChange={(e)=>setModal(v=>({ ...v, form:{...v.form,[k]:e.target.value} }))}/></label>)}</div></Modal>
  </div>;
}

ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
