const { useMemo, useState } = React;

const NAV_ITEMS = ["Dashboard","Client CRM","Quotes","Shipments","Containers","Suppliers & Agents","Customs Documents","Invoices","Tasks","AI Assistant"];
const shipmentStages = ["Booking Confirmed","Cargo Picked Up","Warehouse Received","Customs Clearance","Loaded on Vessel","In Transit","Arrived at Port","Out for Delivery","Delivered"];

const seed = {
  clients:[{id:"C-001",name:"Emma Johnson",company:"Skyline FBA Ventures",country:"USA",type:"Amazon Seller",email:"emma@skylinefba.com",phone:"+1 310 555 0189",whatsapp:"+1 310 555 0189",preferredMethod:"Sea Freight + DDP",lastContact:"2026-05-14",monthlyValue:120000,notes:"Monthly FBA replenishment.",history:["2026-05-14: Requested quote revision."]},{id:"C-002",name:"Oliver Reed",company:"Britannia Imports Ltd",country:"UK",type:"Importer",email:"oliver@britanniaimports.co.uk",phone:"+44 20 7946 0120",whatsapp:"+44 7700 900210",preferredMethod:"Sea Freight",lastContact:"2026-05-13",monthlyValue:94000,notes:"Home organizers/textiles.",history:["2026-05-13: FOB Ningbo rates."]},{id:"C-003",name:"Lena Fischer",company:"Nordic Retail GmbH",country:"Germany",type:"Retailer",email:"lena@nordicretail.de",phone:"+49 40 555 1200",whatsapp:"+49 151 5600 8844",preferredMethod:"Rail + Truck",lastContact:"2026-05-12",monthlyValue:76000,notes:"ETA reliability sensitive.",history:["2026-05-12: HS code needs."]},{id:"C-004",name:"Khalid Mansoor",company:"Desert Bridge Distribution",country:"UAE",type:"Distributor",email:"khalid@desertbridge.ae",phone:"+971 4 220 8800",whatsapp:"+971 50 221 8891",preferredMethod:"Air Freight",lastContact:"2026-05-15",monthlyValue:132000,notes:"Urgent electronics shipments.",history:["2026-05-15: urgent air request."]},{id:"C-005",name:"Faisal Al-Harbi",company:"Riyadh Wholesale Hub",country:"Saudi Arabia",type:"Wholesale Buyer",email:"faisal@rwhub.sa",phone:"+966 11 455 0090",whatsapp:"+966 55 204 1190",preferredMethod:"Sea Freight + Truck",lastContact:"2026-05-11",monthlyValue:88000,notes:"Large furniture consignments.",history:["2026-05-11: Payment follow-up."]}],
  quotes:[{id:"Q-2301",client:"Skyline FBA Ventures",origin:"Shenzhen",destination:"USA",method:"Sea",incoterm:"DDP",cargo:"Amazon FBA goods",qty:1200,cbm:42,gross:11800,chargeable:11800,cost:18650,margin:18,status:"Sent",breakdown:{freight:13000,trucking:1200,customs:900,docs:250,insurance:300,service:3000}},{id:"Q-2302",client:"Britannia Imports Ltd",origin:"Ningbo",destination:"UK",method:"Sea",incoterm:"FOB",cargo:"Home organizers",qty:880,cbm:36,gross:9600,chargeable:9600,cost:14980,margin:15,status:"Negotiating",breakdown:{freight:10800,trucking:900,customs:700,docs:180,insurance:200,service:2200}}],
  shipments:[{id:"S-9901",client:"Skyline FBA Ventures",cargo:"Cosmetics packaging",origin:"Guangzhou",destination:"Los Angeles",mode:"Sea",incoterm:"DDP",cbm:28,weight:7900,container:"MSCU9021456",bl:"OOLU7791023",stage:"In Transit",eta:"2026-05-23",etd:"2026-05-05",supplier:"Guangzhou Beauty Pack Co.",agent:"Pacific Axis USA",value:68000},{id:"S-9902",client:"Britannia Imports Ltd",cargo:"Textiles",origin:"Yiwu",destination:"London",mode:"Rail",incoterm:"FOB",cbm:18,weight:5100,container:"LCL",bl:"RAILUK23901",stage:"Customs Clearance",eta:"2026-05-20",etd:"2026-05-09",supplier:"Yiwu Textile Source",agent:"EuroLink Brokers",value:47000}],
  containers:[{no:"MSCU9021456",type:"40HQ",seal:"SL99871",vessel:"MV Ever Summit",voyage:"EV2309",pol:"Yantian",pod:"Los Angeles",etd:"2026-05-05",eta:"2026-05-23",status:"In Transit",cargo:"Cosmetics packaging",cbm:61,utilization:91}],
  partners:[{company:"Shenzhen Prime Electronics",type:"Chinese Supplier",city:"Shenzhen",contact:"Mr. Lin",wechat:"lin-prime-sz",whatsapp:"+86 138 0012 6631",rating:4.8,leadTime:"5 days",reliability:93,notes:"Consistent export quality."}],
  docs:[{ship:"S-9901",client:"Skyline FBA Ventures",type:"Commercial Invoice",status:"Approved",upload:"2026-05-03",missing:"None",action:"Archive"}],
  invoices:[{id:"INV-2048",client:"Riyadh Wholesale Hub",shipment:"S-9903",amount:32900,issue:"2026-05-01",due:"2026-05-15",payment:"Bank Transfer",balance:12900,margin:17,status:"Overdue"}],
  tasks:[{title:"Follow up with client",assignee:"Nadia",priority:"High",due:"2026-05-17",client:"Skyline FBA Ventures",shipment:"S-9901",status:"In Progress"}],
};

const badgeClass = (s="") => `badge ${s.toLowerCase().replace(/\s+/g,"-")}`;
const stagePct = s => Math.round(((shipmentStages.indexOf(s)+1)/shipmentStages.length)*100);

function Modal({title,children,onClose,onSave}){return <div className="overlay"><div className="modal"><h3>{title}</h3>{children}<div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="primary" onClick={onSave}>Save</button></div></div></div>}

function App(){
  const [tab,setTab]=useState("Dashboard");
  const [selected,setSelected]=useState(null);
  const [search,setSearch]=useState("");
  const [aiText,setAiText]=useState("Select an AI shortcut to generate freight communication.");
  const [db,setDb]=useState(seed);
  const [modal,setModal]=useState(null);
  const [form,setForm]=useState({});

  const metrics=useMemo(()=>({activeClients:db.clients.length,openQuotes:db.quotes.filter(q=>["Draft","Sent","Negotiating"].includes(q.status)).length,activeShipments:db.shipments.filter(s=>s.stage!=="Delivered").length,delayedShipments:db.shipments.filter(s=>new Date(s.eta)<new Date("2026-05-17") && s.stage!=="Delivered").length,monthlyRevenue:db.invoices.reduce((a,i)=>a+i.amount,0),unpaidInvoices:db.invoices.filter(i=>i.balance>0).length,totalCbm:db.shipments.reduce((a,s)=>a+s.cbm,0),totalContainers:db.containers.length,upcomingEtas:db.shipments.filter(s=>new Date(s.eta)>=new Date("2026-05-17")).length,urgentTasks:db.tasks.filter(t=>["Urgent","High"].includes(t.priority)).length}),[db]);

  const openAdd=()=>{
    const map={"Client CRM":{id:`C-${Date.now().toString().slice(-3)}`,name:"",company:"",country:"",type:"",email:"",phone:"",whatsapp:"",preferredMethod:"Sea Freight",lastContact:"2026-05-17",monthlyValue:0,notes:"",history:[]},"Quotes":{id:`Q-${Date.now().toString().slice(-4)}`,client:"",origin:"Shenzhen",destination:"USA",method:"Sea",incoterm:"FOB",cargo:"",qty:0,cbm:0,gross:0,chargeable:0,cost:0,margin:15,status:"Draft",breakdown:{freight:0,trucking:0,customs:0,docs:0,insurance:0,service:0}},"Shipments":{id:`S-${Date.now().toString().slice(-4)}`,client:"",cargo:"",origin:"Guangzhou",destination:"Los Angeles",mode:"Sea",incoterm:"FOB",cbm:0,weight:0,container:"",bl:"",stage:"Booking Confirmed",eta:"2026-05-25",etd:"2026-05-18",supplier:"",agent:"",value:0},"Suppliers & Agents":{company:"",type:"Chinese Supplier",city:"",contact:"",wechat:"",whatsapp:"",rating:4.5,leadTime:"3 days",reliability:85,notes:""},"Invoices":{id:`INV-${Date.now().toString().slice(-4)}`,client:"",shipment:"",amount:0,issue:"2026-05-17",due:"2026-05-30",payment:"Bank Transfer",balance:0,margin:15,status:"Pending"},"Tasks":{title:"",assignee:"",priority:"Medium",due:"2026-05-20",client:"",shipment:"",status:"Open"}};
    if(map[tab]){setForm(map[tab]);setModal(`Add ${tab}`)};
  };

  const saveModal=()=>{const t=tab;if(t==="Client CRM")setDb(v=>({...v,clients:[form,...v.clients]})); if(t==="Quotes")setDb(v=>({...v,quotes:[form,...v.quotes]})); if(t==="Shipments")setDb(v=>({...v,shipments:[form,...v.shipments]})); if(t==="Suppliers & Agents")setDb(v=>({...v,partners:[form,...v.partners]})); if(t==="Invoices")setDb(v=>({...v,invoices:[form,...v.invoices]})); if(t==="Tasks")setDb(v=>({...v,tasks:[form,...v.tasks]})); setModal(null);};

  const filtered=(arr)=>arr.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));

  return <div className="app"><aside className="sidebar"><h1>BZ Global Freight</h1><p>From China to the World, Freight Made Clear</p>{NAV_ITEMS.map(n=><button key={n} className={tab===n?"nav active":"nav"} onClick={()=>{setTab(n);setSelected(null)}}>{n}</button>)}</aside><main className="main"><header className="topbar"><input placeholder="Search clients, shipments, quotes..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={openAdd}>+ Add</button></header>

  {tab==="Dashboard"&&<><section className="metric-grid">{Object.entries(metrics).map(([k,v])=><article className="card" key={k}><h4>{k.replace(/([A-Z])/g," $1")}</h4><strong>{k==="monthlyRevenue"?`$${v.toLocaleString()}`:v}</strong></article>)}</section><section className="metric-grid small">{["Shipments in transit","Pending customs clearance","Payments overdue","Quotes waiting for client approval","Containers arriving this week"].map(c=><article className="card" key={c}><h4>{c}</h4><p>Live freight operational snapshot.</p></article>)}</section></>}
  {tab==="Client CRM"&&<DataTable rows={filtered(db.clients)} onSelect={setSelected} cols={["name","company","country","type","email","phone","whatsapp","preferredMethod","lastContact","monthlyValue"]} extra={(c)=><button onClick={(e)=>{e.stopPropagation();setAiText(`Follow-up email for ${c.company}:\nWe can secure ${c.preferredMethod} space from China this week...`)}}>AI follow-up</button>}/>}
  {tab==="Quotes"&&<DataTable rows={filtered(db.quotes)} onSelect={setSelected} cols={["id","client","origin","destination","method","incoterm","cargo","qty","cbm","gross","chargeable","cost","margin","status"]} onStatus={(q)=>setDb(v=>({...v,quotes:v.quotes.map(i=>i.id===q.id?{...i,status:i.status==="Sent"?"Negotiating":"Sent"}:i)}))}/>}
  {tab==="Shipments"&&<section className="cards">{filtered(db.shipments).map(s=><article key={s.id} className="card" onClick={()=>setSelected(s)}><h3>{s.id} · {s.client}</h3><p>{s.origin} ➜ {s.destination} · {s.mode}/{s.incoterm}</p><p>{s.cargo} · {s.cbm} CBM · {s.weight}kg · BL {s.bl}</p><p>Stage <span className={badgeClass(s.stage)}>{s.stage}</span></p><div className="progress"><span style={{width:`${stagePct(s.stage)}%`}}/></div><small>ETD {s.etd} · ETA {s.eta}</small><button onClick={(e)=>{e.stopPropagation();const ix=shipmentStages.indexOf(s.stage);setDb(v=>({...v,shipments:v.shipments.map(i=>i.id===s.id?{...i,stage:shipmentStages[Math.min(ix+1,shipmentStages.length-1)]}:i)}))}}>Advance Stage</button></article>)}</section>}
  {tab==="Containers"&&<DataTable rows={filtered(db.containers)} onSelect={setSelected} cols={["no","type","seal","vessel","voyage","pol","pod","etd","eta","status","cargo","cbm","utilization"]}/>}
  {tab==="Suppliers & Agents"&&<DataTable rows={filtered(db.partners)} onSelect={setSelected} cols={["company","type","city","contact","wechat","whatsapp","rating","leadTime","reliability","notes"]} extra={(p)=><button onClick={(e)=>{e.stopPropagation();setAiText(`Negotiation brief: ${p.company}\n- Request faster lead time\n- Confirm pickup window\n- Document readiness before cutoff`)}}>AI brief</button>}/>}
  {tab==="Customs Documents"&&<DataTable rows={filtered(db.docs)} onSelect={setSelected} cols={["ship","client","type","status","upload","missing","action"]}/>}
  {tab==="Invoices"&&<DataTable rows={filtered(db.invoices)} onSelect={setSelected} cols={["id","client","shipment","amount","issue","due","payment","balance","margin","status"]} onStatus={(i)=>setDb(v=>({...v,invoices:v.invoices.map(x=>x.id===i.id?{...x,status:x.status==="Pending"?"Paid":"Pending",balance:x.status==="Pending"?0:x.balance}:x)}))}/>}
  {tab==="Tasks"&&<DataTable rows={filtered(db.tasks)} onSelect={setSelected} cols={["title","assignee","priority","due","client","shipment","status"]} onStatus={(t)=>setDb(v=>({...v,tasks:v.tasks.map(x=>x.title===t.title?{...x,status:x.status==="Open"?"In Progress":x.status==="In Progress"?"Done":"Open"}:x)}))}/>}
  {tab==="AI Assistant"&&<section className="card"><h3>BZ Freight AI Assistant</h3><div className="shortcuts">{["Generate shipment update","Write delay apology","Create quote message","Prepare customs checklist","Write payment reminder","Translate supplier message to Chinese","Explain DDP vs FOB to client","Summarize today’s urgent shipments"].map(b=><button key={b} onClick={()=>setAiText(`AI Output: ${b}\n\nPrepared for BZ Global Freight with professional forwarding language.`)}>{b}</button>)}</div><textarea rows="10" value={aiText} readOnly/><div className="modal-actions"><button onClick={()=>navigator.clipboard?.writeText(aiText)}>Copy Message</button></div></section>}

  </main><aside className="detail"><h3>Detail Panel</h3>{selected?<pre>{JSON.stringify(selected,null,2)}</pre>:<p>Select a row/card to inspect details.</p>}</aside>
  {modal&&<Modal title={modal} onClose={()=>setModal(null)} onSave={saveModal}><div className="form-grid">{Object.entries(form).filter(([k])=>k!=="history"&&k!=="breakdown").map(([k,v])=><label key={k}>{k}<input value={v} onChange={e=>setForm(f=>({...f,[k]:e.target.value}))}/></label>)}</div></Modal>}
  </div>
}

function DataTable({rows,cols,onSelect,extra,onStatus}){return <table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}{extra&&<th>actions</th>}{onStatus&&<th>status update</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||r.no||r.company||`${i}`} onClick={()=>onSelect?.(r)}>{cols.map(c=><td key={c}><span className={typeof r[c]==='string'&&["status","priority","stage"].includes(c)?badgeClass(r[c]):""}>{String(r[c])}</span></td>)}{extra&&<td>{extra(r)}</td>}{onStatus&&<td><button onClick={(e)=>{e.stopPropagation();onStatus(r)}}>Update</button></td>}</tr>)}</tbody></table>}

ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
